defaults: &defaults
  service_external_jobs:
    uri_base_auth:      <%= ENV["GIANT_SERVICE_EXTERNAL_JOBS_URI_BASE_AUTH"] %>
    uri_base_rest:      <%= ENV["GIANT_SERVICE_EXTERNAL_JOBS_URI_BASE_REST"] %>
    auth_client_id:     <%= ENV["GIANT_SERVICE_EXTERNAL_JOBS_AUTH_CLIENT_ID"] %>
    auth_client_secret: <%= ENV["GIANT_SERVICE_EXTERNAL_JOBS_AUTH_CLIENT_SECRET"] %>
    auth_username:      <%= ENV["GIANT_SERVICE_EXTERNAL_JOBS_AUTH_USERNAME"] %>
    auth_password:      <%= ENV["GIANT_SERVICE_EXTERNAL_JOBS_AUTH_PASSWORD"] %>
    auth_state:         <%= ENV["GIANT_SERVICE_EXTERNAL_JOBS_AUTH_STATE"] %>

development:
  <<: *defaults
  secret_key_base: <%= ENV["GIANT_SECRET_KEY_BASE_DEVELOPMENT"] %>

test:
  <<: *defaults
  secret_key_base: <%= ENV["GIANT_SECRET_KEY_BASE_TEST"] %>

production:
  <<: *defaults
  secret_key_base: <%= ENV["GIANT_SECRET_KEY_BASE_PRODUCTION"] %>
