defaults: &defaults
  service_external_jobs_uri_base_auth:  'https://auth.bullhornstaffing.com/oauth'
  service_external_jobs_uri_base_rest:  'http://rest.bullhorn.com/rest-services'
  service_external_jobs_auth_client_id: '???'
  service_external_jobs_auth_username:  '???'
  service_external_jobs_auth_password:  '???'
  service_external_jobs_auth_state:     '???'

development:
  <<: *defaults
  secret_key_base: 1fbf233f609711e3ea11d647473194aac5cb071be3b2ef78f039af624eb103543d9853875e72fd033e08cb2ba9d5d5a435aae2ef94ac366501fb7fe4f0fee4e9
 
test:
  <<: *defaults
  secret_key_base: dd6f3e8bff2f5ad0525e30e913dc5b6b086968e5bfe9cea39e44773b276091731d6f174ea08e259dc838c7b4ae5aa085304c1249b947949d13040ba514bcb90a 
 
production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
